DROP TABLE "SILNIKI" CASCADE CONSTRAINTS;                        
DROP TABLE "STANOWISKA" CASCADE CONSTRAINTS;                     
DROP TABLE "KONKRETNYEGZEMPLARZ" CASCADE CONSTRAINTS;            
DROP TABLE "REZYGNACJE" CASCADE CONSTRAINTS;                     
DROP TABLE "ZAMOWIENIA" CASCADE CONSTRAINTS;                     
DROP TABLE "ZATRUDNIENIA" CASCADE CONSTRAINTS;                   
DROP TABLE "DOSTEGZEMPLARZA" CASCADE CONSTRAINTS;  
DROP TABLE "KLIENCI" CASCADE CONSTRAINTS;                   
DROP TABLE "ODDZIALY" CASCADE CONSTRAINTS;  
DROP TABLE "KRAJE" CASCADE CONSTRAINTS;                          
DROP TABLE "RODZAJEPALIWA" CASCADE CONSTRAINTS;                  
DROP TABLE "KOLORY" CASCADE CONSTRAINTS;                         
DROP TABLE "TYPYMOTOCYKLI" CASCADE CONSTRAINTS;                  
DROP TABLE "PERSONEL" CASCADE CONSTRAINTS;                       
DROP TABLE "JAZDYPROBNE" CASCADE CONSTRAINTS;                    
DROP TABLE "SPRZEDANE" CASCADE CONSTRAINTS;                      
DROP TABLE "PRODUCENCI" CASCADE CONSTRAINTS;                     
DROP TABLE "MOTOCYKLE" CASCADE CONSTRAINTS;                      
DROP TABLE "EGZEMPLARZE" CASCADE CONSTRAINTS;  
DROP sequence "ID_KLIENTA_SEQ" 
/
DROP sequence "ID_MIASTA_SEQ" 
/                 
DROP sequence "ID_MOTOCYKLU_SEQ" 
/
DROP sequence "ID_ODDZIALU_SEQ" 
/
DROP sequence "ID_PERSONELU_SEQ" 
/
DROP sequence "ID_SILNIKA_TRIG" 
/
DROP sequence "ID_ZAMOWIENIA_TRIG" ;